# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
puts 'cleaning up database...'
User.destroy_all
puts 'database is clean!'
User.create!(email: "prof@teste.com", teacher_role: true, student_role: true, name: "Fernanda T.", password: '123456')
User.create!(email: "aluno@teste.com", teacher_role: false, student_role: true, name: "Fernanda S.", password: '123456')
#-----------New Questionnaire---------------------------------------
Questionnaire.create!(name: "World Capitals", token: "capitals", user_id: 1)
Question.create!(name:"What is the Capital of Mexico?", questionnaire_id: 1)
Answer.create!(question_id: 1, name:"Mexico City", correct: true)
Answer.create!(question_id: 1, name:"Tijuana", correct: false)
Answer.create!(question_id: 1, name:"Madrid", correct: false)
Answer.create!(question_id: 1, name:"Guadalajara", correct: false)
Question.create!(name:"What is the Capital of France?", questionnaire_id: 1)
Answer.create!(question_id: 2, name:"Versailles", correct: false)
Answer.create!(question_id: 2, name:"Nice", correct: false)
Answer.create!(question_id: 2, name:"Paris", correct: true)
Answer.create!(question_id: 2, name:"Marseille", correct: false)
Question.create!(name:"What is the Capital of India?", questionnaire_id: 1)
Answer.create!(question_id: 3, name:"Mumbai", correct: false)
Answer.create!(question_id: 3, name:"Sri Lanka", correct: false)
Answer.create!(question_id: 3, name:"New Delhi", correct: true)
Answer.create!(question_id: 3, name:"Calcutta", correct: false)
Question.create!(name:"What is the capital of Canada?", questionnaire_id: 1)
Answer.create!(question_id: 4, name:"Montreal", correct: false)
Answer.create!(question_id: 4, name:"Quebec", correct: false)
Answer.create!(question_id: 4, name:"Ottawa", correct: true)
Answer.create!(question_id: 4, name:"Vancouver", correct: false)
#-----------New Questionnaire---------------------------------------
Questionnaire.create!(name: "Ruby Basics", token: "ruby", user_id: 1)
Question.create!(name: "Which of the following datatypes are valid in Ruby?", questionnaire_id: 2)
Answer.create!(question_id: 5, name:"Integer", correct: false)
Answer.create!(question_id: 5, name:"String", correct: false)
Answer.create!(question_id: 5, name:"Boolean", correct: false)
Answer.create!(question_id: 5, name:"All of the mentioned", correct: true)
Question.create!(name: "What is the extension used for saving the ruby file?", questionnaire_id: 2)
Answer.create!(question_id: 6, name:".ry extension", correct: false)
Answer.create!(question_id: 6, name:".rrb extension", correct: false)
Answer.create!(question_id: 6, name:".rb extension", correct: true)
Answer.create!(question_id: 6, name:".ruby extension", correct: false)
Question.create!(name:"Why is the library function 'puts' used for?", questionnaire_id: 2)
Answer.create!(question_id: 7, name:"Prints whatever is given and insert a new(blank) line", correct: true)
Answer.create!(question_id: 7, name:"Prints whatever is given and print it to the screen", correct: false)
Answer.create!(question_id: 7, name:"Gets input from the user", correct: false)
Answer.create!(question_id: 7, name:"Save a new variable", correct: false)
#-----------New Questionnaire---------------------------------------
Questionnaire.create!(name: "The Beatles", token: "help", user_id: 1)
Question.create!(name:"The Beatles were from?", questionnaire_id: 3)
Answer.create!(question_id: 8, name: "London, England", correct: false)
Answer.create!(question_id: 8, name: "New York, NY", correct: false)
Answer.create!(question_id: 8, name: "Hamburg, Germany", correct: false)
Answer.create!(question_id: 8, name: "Liverpool, England", correct: true)
Question.create!(name:"What was the name of the small club in Liverpool where the Beatles got their start?", questionnaire_id: 3)
Answer.create!(question_id: 9, name: "The Comedy Club", correct: false)
Answer.create!(question_id: 9, name: "The Cotton Club", correct: false)
Answer.create!(question_id: 9, name: "The Cavern Club", correct: true)
Answer.create!(question_id: 9, name: "The Chameleon Club", correct: false)
Question.create!(name: "The Beatles first appeared on", questionnaire_id: 3)
Answer.create!(question_id: 10, name: "Saturday Night Live", correct: false)
Answer.create!(question_id: 10, name: "The Ed Sullivan Show", correct: true)
Answer.create!(question_id: 10, name: "The Tonight Show", correct: false)
Answer.create!(question_id: 10, name: "American Bandstand", correct: false)
Question.create!(name: "When did the Beatles break up?", questionnaire_id: 3)
Answer.create!(question_id: 11, name: "At 1968", correct: false)
Answer.create!(question_id: 11, name: "At 1964", correct: false)
Answer.create!(question_id: 11, name: "At 1970", correct: true)
Answer.create!(question_id: 11, name: "At 1969", correct: false)
